apiVersion: v1
entries:
  seethrough:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-06-06T13:17:07.496175318Z"
    description: Lightweight Kubernetes and server monitoring software with alerting
      built-in
    digest: 504dd7eb789f464366a2c57e0f78241f92bf53c5ded7f33912b8201aee851645
    name: seethrough
    type: application
    urls:
    - https://longucodes.github.io/seethrough/charts/seethrough-0.1.0-canary-062d6bb.tgz
    version: 0.1.0-canary-062d6bb
generated: "2026-06-06T13:17:07.495621133Z"
