apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seethrough.fullname" . }}-auth
  labels:
    {{- include "seethrough.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $secretName := include "seethrough.fullname" . | printf "%s-auth" }}
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
  {{- if and $existingSecret $existingSecret.data }}
  jwt-secret: {{ index $existingSecret.data "jwt-secret" | quote }}
  {{- else }}
  jwt-secret: {{ default (randAlphaNum 32) .Values.config.jwtSecret | b64enc | quote }}
  {{- end }}
