apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seethrough.fullname" . }}-auth
  labels:
    {{- include "seethrough.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $secretName := include "seethrough.fullname" . | printf "%s-auth" }}
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
  {{- if and $existingSecret (hasKey $existingSecret.data "jwt-secret") }}
  jwt-secret: {{ index $existingSecret.data "jwt-secret" | quote }}
  {{- else }}
  jwt-secret: {{ default (randAlphaNum 32) .Values.config.jwtSecret | b64enc | quote }}
  {{- end }}
  {{- if and $existingSecret (and $existingSecret.data (and (hasKey $existingSecret.data "admin-username") (hasKey $existingSecret.data "admin-password"))) }}
  admin-username: {{ index $existingSecret.data "admin-username" | quote }}
  admin-password: {{ index $existingSecret.data "admin-password" | quote }}
  {{- else }}
  admin-username: {{ default (randAlphaNum 8 | printf "admin-%s") .Values.config.defaultAdmin.username | b64enc | quote }}
  admin-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
---