{{- if .Values.storage.postgres.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: {{ .Values.storage.postgres.host }}
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_USER
              value: {{ .Values.storage.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.storage.postgres.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.storage.postgres.db | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.storage.postgres.persistence.storageClass }}
        storageClassName: {{ .Values.storage.postgres.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.storage.postgres.persistence.size | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.storage.postgres.host }}
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
{{ end }}
{{ if .Values.storage.redis.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: {{ .Values.storage.redis.host }}
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.storage.redis.persistence.storageClass }}
        storageClassName: {{ .Values.storage.redis.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.storage.redis.persistence.size | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.storage.redis.host }}
spec:
  ports:
    - port: 6379
  selector:
    app: redis
{{- end }}
